/**
 * Asignar Rol Menu Screen Module - REDISEÑADO
 * Gestión de permisos con flag de escritura (write)
 * Roles 2-5 solamente.
 */

const AsignarRolMenuScreen = {
    name: 'asignarolmenu',

    template: () => `
        <div class="h-full flex flex-col p-4 md:p-6">
            <!-- Header -->
            <div class="mb-4 flex items-center gap-4 pb-4 border-b border-gray-300">
                <img style="width:3em" src="img/asignarol.png" alt="Icono" onerror="this.style.display='none'">
                <h1 class="text-2xl font-bold text-gray-800">Asignación de Roles a Menús (Lectura/Escritura)</h1>
                <div class="flex-grow"></div>

                <button id="btn-ayuda-arm"
                    class="flex items-center justify-center gap-2 rounded-md shadow-md transition-all duration-300 hover:shadow-lg hover:-translate-y-0.5 text-white font-medium text-sm"
                    style="width: 140px; padding: 0.5rem 0.75rem; background: linear-gradient(180deg, #aad2eb 0%, #8c9bc4 100%); border: 0.5px solid #888;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <circle cx="12" cy="12" r="10"></circle>
                        <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                        <line x1="12" y1="17" x2="12.01" y2="17"></line>
                    </svg>
                    <span>Ayuda</span>
                </button>

                <button id="btn-salir-arm"
                    class="gradiente hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg shadow-md transition-transform transform hover:scale-105 flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                        <polyline points="16 17 21 12 16 7"></polyline>
                        <line x1="21" y1="12" x2="9" y2="12"></line>
                    </svg>
                    <span>Salir</span>
                </button>
            </div>

            <!-- Main Content -->
            <div class="flex-grow flex gap-6 overflow-hidden">

                <!-- Left Panel: Roles (Source) -->
                <div class="w-1/3 bg-white rounded-lg shadow-lg p-6 flex flex-col">
                    <h2 class="text-xl font-bold text-gray-700 mb-4 flex items-center gap-2">
                        <i class="fas fa-user-tag text-blue-600"></i>
                        Roles Disponibles
                    </h2>
                    <p class="text-sm text-gray-500 mb-4">Arrastra "Solo Lectura" o "Full" hacia un menú.</p>
                    <div id="roles-container-arm" class="flex flex-col gap-4 overflow-y-auto pr-2">
                        <!-- Roles generated by JS -->
                    </div>
                </div>

                <!-- Right Panel: Menu Tree (Target) -->
                <div class="flex-1 bg-white rounded-lg shadow-lg p-6 flex flex-col">
                    <h2 class="text-xl font-bold text-gray-700 mb-4 flex items-center gap-2">
                        <i class="fas fa-sitemap text-green-600"></i>
                        Árbol de Menús (Admin Excluido)
                    </h2>
                    <p class="text-sm text-gray-500 mb-4">Arrastra roles para asignar/cambiar. Arrastra fuera para eliminar.</p>
                    <div id="menu-container-arm"
                        class="flex-1 overflow-y-auto flex flex-col gap-1 border rounded p-2 bg-gray-50">
                        <!-- Menu Tree generated by JS -->
                    </div>
                </div>
            </div>
            
            <!-- Help Modal -->
            <div id="help-modal-arm">
                <div id="help-modal-header-arm">
                    <span class="font-bold">Manual Asignación Roles</span>
                    <div>
                         <button id="maximize-help-arm" title="Maximizar / Abrir en nueva pestaña" class="text-white hover:text-gray-200 hover:bg-blue-700 rounded p-1 transition-colors mr-2">
                             <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                 <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
                                 <polyline points="15 3 21 3 21 9"></polyline>
                                 <line x1="10" y1="14" x2="21" y2="3"></line>
                             </svg>
                         </button>
                         <button id="close-help-arm" class="text-white hover:text-gray-200 hover:bg-blue-700 rounded p-1 transition-colors">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <line x1="18" y1="6" x2="6" y2="18"></line>
                                <line x1="6" y1="6" x2="18" y2="18"></line>
                            </svg>
                         </button>
                    </div>
                </div>
                <iframe id="help-iframe-arm" class="flex-grow w-full border-none"></iframe>
            </div>

            <style>
                .role-button { cursor: grab; transition: all 0.2s; }
                .role-button:active { cursor: grabbing; }
                .role-button.dragging { opacity: 0.5; }
                
                .menu-row { transition: all 0.2s; }
                .menu-row.drag-over { background-color: #dbeafe !important; border-left: 4px solid #3b82f6; }
                
                .role-badge { animation: fadeIn 0.3s; cursor: grab; }
                .role-badge:active { cursor: grabbing; }

                /* Specific Colors for Roles */
                /* Rol 2: Green */
                .rol-2-read { background-color: #86efac; color: #166534; border: 1px solid #166534; } /* Light Green */
                .rol-2-full { background-color: #15803d; color: white; border: 1px solid #166534; } /* Dark Green */
                
                /* Rol 3: Yellow */
                .rol-3-read { background-color: #fde047; color: #854d0e; border: 1px solid #854d0e; } /* Light Yellow */
                .rol-3-full { background-color: #ca8a04; color: white; border: 1px solid #854d0e; } /* Dark Yellow */
                
                /* Rol 4: Red */
                .rol-4-read { background-color: #fca5a5; color: #991b1b; border: 1px solid #991b1b; } /* Light Red */
                .rol-4-full { background-color: #b91c1c; color: white; border: 1px solid #991b1b; } /* Dark Red */
                
                /* Rol 5: Purple */
                .rol-5-read { background-color: #d8b4fe; color: #6b21a8; border: 1px solid #6b21a8; } /* Light Purple */
                .rol-5-full { background-color: #7e22ce; color: white; border: 1px solid #6b21a8; } /* Dark Purple */

                /* Help Modal */
                #help-modal-arm {
                    position: fixed; top: 10%; right: 10%; width: 50%; height: 60%;
                    background-color: white; border: 1px solid #d1d5db; box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                    z-index: 1000; display: none; flex-direction: column; resize: both; overflow: hidden;
                    min-width: 400px; min-height: 300px; border-radius: 8px;
                }
                #help-modal-header-arm {
                    background: linear-gradient(180deg, #aad2eb 0%, #8c9bc4 100%);
                    color: white; padding: 10px 15px; cursor: move; display: flex; justify-content: space-between; align-items: center;
                }
            </style>
        </div>
    `,

    init: async (params = {}) => {

        const self = AsignarRolMenuScreen;
        const token = sessionStorage.getItem('authToken');

        if (!token) {
            navigate('dashboard');
            return;
        }

        self.draggedItem = null; // { rolID, write (0/1), fromMenuID (null if source) }
        self.isDraggingHelp = false;

        self.renderRoles();
        await self.loadMenus(token);
        self.setupEventListeners(token);
    },

    setupEventListeners: (token) => {
        const self = AsignarRolMenuScreen;

        document.getElementById('btn-salir-arm')?.addEventListener('click', () => {
            navigate('dashboard');
        });

        document.body.addEventListener('dragover', self.handleGlobalDragOver);
        document.body.addEventListener('drop', (e) => self.handleGlobalDrop(e, token));

        self.setupHelp();
    },

    destroy: () => {
        const self = AsignarRolMenuScreen;
        document.body.removeEventListener('dragover', self.handleGlobalDragOver);
        // Note: Global drop removal limitation
    },

    handleGlobalDragOver: (e) => {
        const self = AsignarRolMenuScreen;
        if (self.draggedItem && self.draggedItem.fromMenuID) {
            e.preventDefault(); // Permitir drop para eliminar
        }
    },

    handleGlobalDrop: async (e, token) => {
        const self = AsignarRolMenuScreen;
        // Si viene de un menú y cae fuera del container de menús => Eliminar
        if (self.draggedItem && self.draggedItem.fromMenuID && !e.target.closest('#menu-container-arm')) {
            e.preventDefault();
            await self.updateMenuRole(self.draggedItem.fromMenuID, self.draggedItem.rolID, 0, false, token); // assign=false
        }
        self.draggedItem = null;
        document.querySelectorAll('.drag-over').forEach(el => el.classList.remove('drag-over'));
    },

    renderRoles: () => {
        const container = document.getElementById('roles-container-arm');
        const roles = [
            { id: 2, name: 'Rol 2' },
            { id: 3, name: 'Rol 3' },
            { id: 4, name: 'Rol 4' },
            { id: 5, name: 'Rol 5' }
        ];

        container.innerHTML = roles.map(role => `
            <div class="border p-3 rounded-lg shadow-sm bg-gray-50">
                <div class="font-bold text-gray-700 mb-2">${role.name}</div>
                <div class="flex gap-2">
                    <div draggable="true" 
                         data-rol-id="${role.id}"
                         data-write="0"
                         class="role-button rol-${role.id}-read py-2 px-3 rounded text-xs font-bold w-1/2 text-center flex items-center justify-center gap-1 shadow-sm hover:shadow-md">
                        <i class="fas fa-eye"></i> Solo Lectura
                    </div>
                    <div draggable="true" 
                         data-rol-id="${role.id}"
                         data-write="1"
                         class="role-button rol-${role.id}-full py-2 px-3 rounded text-xs font-bold w-1/2 text-center flex items-center justify-center gap-1 shadow-sm hover:shadow-md">
                        <i class="fas fa-edit"></i> Full
                    </div>
                </div>
            </div>
        `).join('');

        // Listeners
        container.querySelectorAll('.role-button').forEach(btn => {
            btn.addEventListener('dragstart', (e) => {
                AsignarRolMenuScreen.draggedItem = {
                    rolID: e.target.dataset.rolId,
                    write: parseInt(e.target.dataset.write),
                    fromMenuID: null
                };
                e.target.classList.add('dragging');
                e.dataTransfer.effectAllowed = 'copy';
            });
            btn.addEventListener('dragend', (e) => e.target.classList.remove('dragging'));
        });
    },

    loadMenus: async (token) => {
        const self = AsignarRolMenuScreen;
        try {
            const response = await fetch('/api/admin/rol-menus', {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            if (!response.ok) throw new Error('Error al cargar menús.');
            const menus = await response.json();
            self.renderMenuTree(menus, token);
        } catch (error) {
            showToast(error.message, 'error');
        }
    },

    renderMenuTree: (menus, token) => {
        const self = AsignarRolMenuScreen;
        const container = document.getElementById('menu-container-arm');
        if (!container) return;

        container.innerHTML = '';
        menus.forEach(menu => {
            const row = document.createElement('div');
            row.className = 'menu-row bg-white hover:bg-gray-100 p-2 rounded shadow-sm flex items-center justify-between border-l-4 border-transparent transition-colors';
            row.dataset.menuId = menu.menuID;

            const depth = (menu.nivel.match(/\./g) || []).length;
            const paddingLeft = depth * 2;
            const icon = depth === 0 ? 'fa-folder' : 'fa-file';

            // Render assigned roles badges
            let rolesHtml = '';
            for (let i = 2; i <= 5; i++) {
                // El backend devuelve rm2.write como 0, 1 o NULL
                const writeVal = menu[`rol${i}`];

                if (writeVal !== null && writeVal !== undefined) {
                    const isFull = writeVal === 1;
                    const cssClass = isFull ? `rol-${i}-full` : `rol-${i}-read`;
                    const iconClass = isFull ? 'fa-pen' : 'fa-eye';
                    const text = isFull ? `R${i} Full` : `R${i} Read`;

                    rolesHtml += `
                        <span draggable="true" 
                              data-rol-id="${i}"
                              data-write="${writeVal}"
                              data-menu-id="${menu.menuID}"
                              class="role-badge ${cssClass} ml-1 px-2 py-0.5 rounded text-xs font-semibold cursor-grab shadow-sm inline-flex items-center gap-1" 
                              title="Arrastrar fuera para eliminar">
                            <i class="fas ${iconClass} text-[10px]"></i> ${text}
                        </span>`;
                }
            }

            row.innerHTML = `
                <div class="flex items-center gap-2 overflow-hidden" style="margin-left: ${paddingLeft}rem;">
                    <i class="fas ${icon} text-gray-400"></i>
                    <span class="font-medium text-gray-700 truncate" title="${menu.menu}">${menu.menu}</span>
                </div>
                <div class="flex items-center gap-1 flex-wrap justify-end">
                    ${rolesHtml}
                </div>
            `;
            container.appendChild(row);
        });

        self.addMenuEventListeners(token);
    },

    addMenuEventListeners: (token) => {
        const self = AsignarRolMenuScreen;

        // Rows as drop targets
        document.querySelectorAll('.menu-row').forEach(row => {
            row.addEventListener('dragover', (e) => {
                e.preventDefault();
                e.currentTarget.classList.add('drag-over');
            });
            row.addEventListener('dragleave', (e) => e.currentTarget.classList.remove('drag-over'));
            row.addEventListener('drop', (e) => self.handleDropOnMenu(e, token));
        });

        // Badges as draggable (to unassign or move)
        document.querySelectorAll('#menu-container-arm .role-badge').forEach(badge => {
            badge.addEventListener('dragstart', (e) => {
                AsignarRolMenuScreen.draggedItem = {
                    rolID: badge.dataset.rolId,
                    write: parseInt(badge.dataset.write),
                    fromMenuID: badge.dataset.menuId
                };
                e.stopPropagation();
                e.dataTransfer.effectAllowed = 'move';
            });
        });
    },

    handleDropOnMenu: async (e, token) => {
        e.preventDefault();
        const self = AsignarRolMenuScreen;
        const row = e.currentTarget;
        row.classList.remove('drag-over');
        const targetMenuID = row.dataset.menuId;

        if (!self.draggedItem) return;

        // Si arrastro desde un menu al mismo menu, no hacemos nada
        if (self.draggedItem.fromMenuID === targetMenuID) return;

        // Asignar (Upsert)
        await self.updateMenuRole(targetMenuID, self.draggedItem.rolID, self.draggedItem.write, true, token);
    },

    updateMenuRole: async (menuID, rolID, write, assign, token) => {
        const self = AsignarRolMenuScreen;
        try {
            const response = await fetch('/api/rol-menu', {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ menuID, rolID, write, assign })
            });

            const result = await response.json();
            if (!response.ok) throw new Error(result.message);

            showToast(result.message, 'success');
            self.loadMenus(token); // Reload to reflect recursive changes
        } catch (error) {
            showToast(error.message, 'error');
        }
    },

    setupHelp: () => {
        // Reuse help logic... (same as before)
        const self = AsignarRolMenuScreen;
        const modal = document.getElementById('help-modal-arm');
        const iframe = document.getElementById('help-iframe-arm');
        const header = document.getElementById('help-modal-header-arm');
        const manualPath = 'ayudas/manual_asignarolmenu.html';

        document.getElementById('btn-ayuda-arm')?.addEventListener('click', () => {
            if (iframe.src.indexOf(manualPath) === -1) iframe.src = manualPath;
            modal.style.display = 'flex';
        });

        document.getElementById('close-help-arm')?.addEventListener('click', () => modal.style.display = 'none');
        document.getElementById('maximize-help-arm')?.addEventListener('click', () => {
            modal.style.display = 'none';
            window.open(manualPath, '_blank');
        });

        if (header) {
            header.addEventListener('mousedown', (e) => {
                if (e.target.closest('button')) return;
                self.isDraggingHelp = true;
                self.startXHelp = e.clientX;
                self.startYHelp = e.clientY;
                const rect = modal.getBoundingClientRect();
                self.initialLeftHelp = rect.left;
                self.initialTopHelp = rect.top;
                modal.style.left = self.initialLeftHelp + 'px';
                modal.style.top = self.initialTopHelp + 'px';
                document.body.style.userSelect = 'none';
            });
            document.addEventListener('mousemove', (e) => {
                if (!self.isDraggingHelp) return;
                const modal = document.getElementById('help-modal-arm');
                if (modal) {
                    modal.style.left = (self.initialLeftHelp + e.clientX - self.startXHelp) + 'px';
                    modal.style.top = (self.initialTopHelp + e.clientY - self.startYHelp) + 'px';
                }
            });
            document.addEventListener('mouseup', () => {
                self.isDraggingHelp = false;
                document.body.style.userSelect = '';
            });
        }
    }
};

if (window.SpaRouter) {
    window.SpaRouter.registerScreen('asignarolmenu', AsignarRolMenuScreen);
}

window.AsignarRolMenuScreen = AsignarRolMenuScreen;
